name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jpegoptim
        run: |
          sudo apt-get update
          sudo apt-get install -y jpegoptim

      - name: Set up Stack
        uses: haskell/actions/setup@v1
        with:
          stack-version: '2.7.1'   # pick your desired Stack CLI version

      - name: Cache GHC installation
        id: ghc
        uses: actions/cache@v3
        with:
          path: ~/.stack/programs/*/ghc-*
          key: ghc-${{ env.GHC_VERSION }}

      - name: Install GHC via Stack
        if: steps.ghc.outputs.cache-hit != 'true'
        run: stack setup --no-terminal

      - name: Cache Pantry
        id: pantry
        uses: actions/cache@v3
        with:
          path: ~/.stack/pantry
          key: pantry-${{ env.STACK_LTS }}

      - name: Restore Pantry
        if: steps.pantry.outputs.cache-hit != 'true'
        run: stack update --no-terminal

      - name: Cache Haskell dependencies
        id: deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack/stack.sqlite3
            ~/.stack/snapshots
          key: deps-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: |
            deps-

      - name: Install project dependencies
        if: steps.deps.outputs.cache-hit != 'true'
        run: stack build --only-dependencies --no-terminal

      - name: Cache project build state
        id: build
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: build-${{ hashFiles('stack.yaml.lock') }}

      - name: Build with Stack
        run: stack build --no-terminal

      - name: Build static site
        run: |
          npm install
          npm run build
          stack exec site -- build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
