name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jpegoptim
        run: |
          sudo apt-get update
          sudo apt-get install -y jpegoptim

      - name: Set up Stack
        uses: actions-hs/setup-stack@v2
        with:
          stack-version: '2.7.1'   # pick your desired Stack CLI version

      - name: Cache Stack and GHC
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            ~/.ghc
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Setup GHC
        run: stack setup --no-terminal

      - name: Install project dependencies
        run: stack build --only-dependencies --no-terminal

      - name: Build with Stack
        run: stack build --no-terminal

      - name: Build static site
        run: |
          npm install
          npm run build
          stack exec site -- build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
